name: A workflow to build an application
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build the app
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Setup .NET
      if: success() || failure()
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      if: success() || failure()
      run: dotnet restore
    - name: Build
      if: success() || failure()
      run: dotnet build -c release --no-restore
    - name: Upload a Build Artifact
      if: success() || failure()
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: trophy #.zip will be added automatically
        path: bin/release/net8.0/*.*
